"""Add item unit table

Revision ID: 22b7e547e2b5
Revises: d22de2daa21c
Create Date: 2025-05-01 05:11:17.488119

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '22b7e547e2b5'
down_revision = 'd22de2daa21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_unit',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_item_unit_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_unit'))
    )
    op.add_column('item', sa.Column('item_unit_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('fk_item_item_unit_id_item_unit'), 'item', 'item_unit', ['item_unit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_item_item_unit_id_item_unit'), 'item', type_='foreignkey')
    op.drop_column('item', 'item_unit_id')
    op.drop_table('item_unit')
    # ### end Alembic commands ###
