"""Fix supplier typo relation

Revision ID: 29a96d3305bf
Revises: 435c6018b0d9
Create Date: 2025-05-04 08:56:42.398316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '29a96d3305bf'
down_revision = '435c6018b0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
