"""Initialize database

Revision ID: 3effc6deb06a
Revises:
Create Date: 2025-05-09 07:01:05.099915

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3effc6deb06a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_transaction',
    sa.Column('type', sa.Enum('income', 'expense', 'transfer_in', 'transfer_out', name='accounttransactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference_name', sa.Enum('sale', 'purchase', 'payable', 'receivable', name='referencename'), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_account_transaction_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_account_transaction_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_transaction'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_transaction')
    # ### end Alembic commands ###
