"""Add sale and sale item table

Revision ID: 8c34df2f57dd
Revises: b5fb2c4239e5
Create Date: 2025-05-07 06:20:46.419879

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8c34df2f57dd'
down_revision = 'b5fb2c4239e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
