"""Resolve typo in sale table

Revision ID: 9c452f68b64e
Revises: 3effc6deb06a
Create Date: 2025-05-09 07:13:04.445260

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c452f68b64e'
down_revision = '3effc6deb06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('date_sale', sa.DateTime(), nullable=False))
    op.drop_column('sale', 'date_sol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('date_sol', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('sale', 'date_sale')
    # ### end Alembic commands ###
