"""Remove unused unit column

Revision ID: b501677b8398
Revises: 22b7e547e2b5
Create Date: 2025-05-01 06:11:46.984697

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b501677b8398'
down_revision = '22b7e547e2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
