"""Add timestamp into item category

Revision ID: d22de2daa21c
Revises: 7b45a6a92094
Create Date: 2025-05-01 04:06:49.713557

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd22de2daa21c'
down_revision = '7b45a6a92094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_category', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('item_category', sa.Column('date_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_category', 'date_updated')
    op.drop_column('item_category', 'date_created')
    # ### end Alembic commands ###
