"""Add store table

Revision ID: d29aaba64216
Revises: d9c75c87a07a
Create Date: 2025-05-03 23:44:29.173571

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd29aaba64216'
down_revision = 'd9c75c87a07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
