"""Add date_created and date updated on user table

Revision ID: d9c75c87a07a
Revises: b501677b8398
Create Date: 2025-05-01 21:48:24.939072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd9c75c87a07a'
down_revision = 'b501677b8398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('date_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_updated')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
