"""Add payment table and remove date updated

Revision ID: e3043ea56aa8
Revises: f529e7def63b
Create Date: 2025-05-09 07:35:56.357993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3043ea56aa8'
down_revision = 'f529e7def63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('date_payment', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('cash', 'transfer', name='paymentmethod'), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('is_reversal', sa.Boolean(), nullable=False),
    sa.Column('is_reversal_payment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_payment_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_payment_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.drop_column('account_transaction', 'date_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_transaction', sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_table('payment')
    # ### end Alembic commands ###
