"""Add quantity and remove owner_id

Revision ID: f529e7def63b
Revises: 9c452f68b64e
Create Date: 2025-05-09 07:24:42.585757

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f529e7def63b'
down_revision = '9c452f68b64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_constraint('fk_purchase_item_owner_id_user', 'purchase_item', type_='foreignkey')
    op.drop_column('purchase_item', 'owner_id')
    op.drop_constraint('fk_sale_item_owner_id_user', 'sale_item', type_='foreignkey')
    op.drop_column('sale_item', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_item', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_sale_item_owner_id_user', 'sale_item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchase_item', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_purchase_item_owner_id_user', 'purchase_item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('purchase_item', 'quantity')
    # ### end Alembic commands ###
