"""Normalize date columns excluding created and updated

Revision ID: fee73affafdf
Revises: 8c34df2f57dd
Create Date: 2025-05-07 06:36:11.175421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fee73affafdf'
down_revision = '8c34df2f57dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('date_purchase', sa.DateTime(), nullable=False))
    op.drop_column('purchase', 'date_purchased')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('date_purchased', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('purchase', 'date_purchase')
    # ### end Alembic commands ###
